version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: harmonia-server
    ports:
      - "4000:4000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/harmonia
      - JWT_SECRET=yourSuperSecretKey
      - PORT=4000
    volumes:
      - ./server:/app
      - ./server/uploads:/app/uploads
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: harmonia-client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  mongo-data:
